name: Pull request coverage (Push)
on: [pull_request]

jobs:
  unit-tests3_8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - run: pip install .
      - run: pip install pytest==5.4.3 pytest-codestyle==2.0.1 pytest-pydocstyle==2.2.0 pytest-cov==2.11.1
      - run: pytest . 2>&1 | tee salida.txt
      # - run: ls
      # - run: cat salida.txt
      # - run: |
      #     tty=$(readlink /proc/$$/fd/2)
      #     read pytest . | tee /dev/tty | grep 'TOTAL\s\+[0-9]\+\s\+[0-9]\+\s\+\([0-9]\{1,3\}\.\?\%\)$' | grep -o '[0-9]\{1,3\}\%' < $tty
      # - run: pytest . | tee /dev/tty | grep 'TOTAL\s\+[0-9]\+\s\+[0-9]\+\s\+\([0-9]\{1,3\}\.\?\%\)$' | grep -o '[0-9]\{1,3\}\%'
      - name: Write cov
        run: |
          echo ${{ github.event_name }}
          green_point=$'\U0001F7E2'
          coverage=$(cat salida.txt | grep 'TOTAL\s\+[0-9]\+\s\+[0-9]\+\s\+\([0-9]\{1,3\}\.\?\%\)$' | grep -o '[0-9]\{1,3\}\%')
          echo ${coverage}

          curl --request POST \
          --url https://api.github.com/repos/experimentacion-github/public-repository/statuses/${{ github.event.pull_request.head.sha }} \
          --header 'authorization: Bearer ${{ secrets.PERSONAL_TOKEN }}' \
          --header 'Accept: application/vnd.github.v3+json' \
          --data '{"state": "success", "description": "'"$coverage"'", "context": "code-cov"}'

          curl --request POST \
          --url https://api.github.com/repos/experimentacion-github/public-repository/issues/${{ github.event.pull_request.number }}/comments \
          --header 'authorization: Bearer ${{ secrets.PERSONAL_TOKEN}}' \
          --header 'Accept: application/vnd.github.v3+json' \
          --data '{"body": "'"$green_point $coverage Coverage"'"}'
        # if: github.event_name == 'pull_request'
      # - name: Write comment
      #   run: |
      #     # bell=$'\360\237\224\224'
      #     bell=$'\U0001F514'
      #     echo ${bell}
      #     curl --request POST \
      #     --url https://api.github.com/repos/experimentacion-github/public-repository/issues/${{ github.event.pull_request.number }}/comments \
      #     --header 'authorization: Bearer ${{ secrets.PERSONAL_TOKEN}}' \
      #     --header 'Accept: application/vnd.github.v3+json' \
      #     --data '{"body": "'"$bell Otro comentario de prueba"'"}'
      - name: List pull request files
        run: |
          curl --request GET \
          --url https://api.github.com/repos/experimentacion-github/public-repository/pulls/${{ github.event.pull_request.number }}/files \
          --header 'authorization: Bearer ${{ secrets.PERSONAL_TOKEN}}' \
          --header 'Accept: application/vnd.github.v3+json'
      # - uses: actions/upload-artifact@v2
      #   with:
      #     name: coverage-report
      #     path: cover/
      #     retention-days: 1