name: Tests

on: [push, pull_request]

jobs:
  # unit-tests3_8:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - run: pip install .
  #     - run: pip install pytest==5.4.3 pytest-codestyle==2.0.1 pytest-pydocstyle==2.2.0 pytest-cov==2.11.1
  #     - run: pytest .
  #     - uses: actions/upload-artifact@v2
  #       with:
  #         name: coverage-report
  #         path: cover/
  #         retention-days: 1

  # codecov:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: "Upload coverage to Codecov"
  #       uses: codecov/codecov-action@v2
  #       with:
  #         fail_ci_if_error: true
  run:
    runs_on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install
        run: pip install .
      - name: Run tests and collect coverage
        run: |
          pip install pytest==5.4.3 pytest-codestyle==2.0.1 pytest-pydocstyle==2.2.0 pytest-cov==2.11.1
          pytest .
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
